# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.logo.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'logo', 'function_path': 'animated_java:logo/animations/loop/resume'}
tag @s add aj.logo.animation.loop.playing