# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:logo/animations/loop/zzz/apply_frame {frame: 90}
scoreboard players add @s aj.loop.frame 1