# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.logo.root] run return 0
execute on passengers if entity @s[tag=aj.logo.data] unless data entity @s {data:{rigHash: '011878bbe20f0ca6ffe200976829119a9d86572a83cd4391dc09a8bad2234bb3'}} on vehicle run function animated_java:logo/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1